# Generated by Django 2.0.6 on 2018-09-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180918_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='foto',
            field=models.ImageField(default='none.png', upload_to='img', verbose_name='Foto'),
            preserve_default=False,
        ),
    ]
